theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Ayush Shridhar
description: About me
google_analytics: G-M4Y4RXQNPE
include: [".well-known"]
permalink: .well-known/keybase.txt
